{{ if .Values.NetworkPolicy.Enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    chart: {{ template "osg-hosted-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
      chart: {{ template "osg-hosted-ce.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "osg-hosted-ce.name" . }}
          chart: {{ template "osg-hosted-ce.chart" . }}
          release: {{ .Release.Name }}
          instance: {{ .Values.Instance | quote }}
    {{- range .Values.NetworkPolicy.AllowedCIDRs}}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 9619
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 80
{{ end }}
